### ISSUE TITLE
Metadata key contains illegal characters

### ISSUE THREAD

**Issue by pjm17971** [googleapis/nodejs-pubsub#667]
Seeing many of these per day:

```
Error: Failed to "modifyAckDeadline" for 202 message(s).
Reason: Metadata key "@" contains illegal characters
```

Maybe related:
https://github.com/googleapis/nodejs-datastore/issues/415

#### Environment details

  - OS: GKE
  - Node.js version: 10.10.x
  - npm version:
  - `@google-cloud/pubsub` version: 0.30.0

**Comment by callmehiphop** [comment]
@pjm17971 0.30.0 made the switch to grpc-js, so it likely is a duplicate of https://github.com/googleapis/nodejs-datastore/issues/415. You might consider pinning to 0.29.0 until we get this sorted out.

FYI @sduskis @alexander-fenster 

I'm going to close this out, but I would suggest subscribing to the aforementioned Datastore issue for updates.

**Comment by pjm17971** [comment]
@callmehiphop we've rolled back to 0.29.0. Just wanted to make sure you guys were aware that the grpc-js library change affected the pubsub client too. But I guess you're on it. Thanks!

**Comment by alexander-fenster** [comment]
Hi @pjm17971,

We have released google-gax v1.1.5 that pulls @grpc/grpc-js v0.5.2 in which the invalid headers (that are coming from Node.js http2 module) are printed in a warning, but do not throw exception. Please upgrade your dependencies, it should fix the problem for you.

Thanks!

**Comment by mahaben** [comment]
Hi @alexander-fenster,

We still have the error `Metadata key "a" contains illegal characters`. We use `@google-cloud/pubsub version: 1.0.0`

Any idea? 

Thanks,

**Comment by alexander-fenster** [comment]
Hi @mahaben,

This error comes from Node.js `http2` stack (https://github.com/nodejs/node/issues/28632) and we don't have any solution at this moment, but we made sure we only print a warning and not an error. Make sure you update your dependencies.

```
npm ls @grpc/grpc-js
```

Starting from `@grpc/grpc-js` v0.5.2 this error is changed to warning so it should not crash your code.

We keep trying to catch and debug it, but since it's something happening in Node.js core, it might take more time.
