### ISSUE TITLE
Lease message do no work for long running jobs

### ISSUE THREAD

**Issue by muryginm** [googleapis/nodejs-pubsub#83]
Hi, 
#### Environment details

  - OS: Ubuntu 16.04
  - Node.js version: 8.9.4
  - npm version: 5.6.0
  - @google-cloud/pubsub version: 0.16.4

In [that issue](https://github.com/googleapis/nodejs-pubsub/issues/81) @callmehiphop mentioned the following:
> Even if we allowed the deadline to be set, the current code would overwrite it and your message would not get redelivered until your subscription object was closed.

But the message **get redelivered** even when `subscription.close` and `message.ack` are not called.

#### Steps to reproduce
  1. Create topic and subscription
  2. Subscribe to message event
  3. Publish message
  4. Do not call `ack` or `nack` in message handler. Count the number that message handler was called during at least 120 seconds.

```javascript
it('should not redeliver message until subscription is closed', function (done) {
    subscription.on('error', done);

    const onMessage = sinon.spy();
    subscription.on('message', onMessage);

    topic
        .publisher()
        .publish(Buffer.from(uuid()))
        .catch(done);

    setTimeout(() => {
        try {
            sinon.assert.calledOnce(onMessage);
            done();
        } catch (error) {
            done(error);
        }
    }, 120000);
});
```
If you want to run this test you could clone [this repository](https://github.com/muryginm/google-cloud-pubsub-issues).

I almost always have the broken test. Does It mean that lease message does not work?

**Comment by callmehiphop** [comment]
Thanks for reporting!

> Does It mean that lease message does not work?

It should. I'm not sure if the server-side fix has been pushed yet, but in some cases PubSub will redeliver messages when a stream is opened/closed. However I suspect this could actually be related to https://github.com/googleapis/nodejs-pubsub/issues/13.

I'm hoping to have a fix for this either today/this weekend. If you're not busy I might ask you to give it a test ride :)

**Comment by callmehiphop** [comment]
@muryginm we've got a fix prepared for this (#92) if you have the bandwidth to test it out that would be fantastic! Otherwise we should have it released within the next day or two.

**Comment by muryginm** [comment]
@callmehiphop 
The issue still exists. During 3 minues I received the same message about 4 times. [You could check it by yourself](https://github.com/muryginm/google-cloud-pubsub-issues/tree/refactor-flow-control).

In addition to this issue I received a lot of new errors which were reported to `subscription.error` event. The new errors stack trace:

```
Error: 14 UNAVAILABLE: The service was unable to fulfill your request. Please try again. [code=8a75]
    at createStatusError (/home/username/pr/google-cloud-pubsub-issues/node_modules/grpc/src/client.js:64:15)
    at ClientDuplexStream._emitStatusIfDone (/home/username/pr/google-cloud-pubsub-issues/node_modules/grpc/src/client.js:270:19)
    at ClientDuplexStream._receiveStatus (/home/username/pr/google-cloud-pubsub-issues/node_modules/grpc/src/client.js:248:8)
    at /home/muryginms/pr/google-cloud-pubsub-issues/node_modules/grpc/src/client.js:804:12
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'The service was unable to fulfill your request. Please try again. [code=8a75]'
```

I suppose you should at least look at this new issue before release.

**Comment by callmehiphop** [comment]
@muryginm I've opened a separate PR (#99) which looks to resolve this issue. If you have the bandwidth to test it/confirm that would be awesome.

**Comment by muryginm** [comment]
@callmehiphop 
Thanks for the work! The issue still exists but it occurs much rarely. Sometimes a message get redelivered after ~60 seconds, sometimes it does not.

I could create a pull request with this test. But it is not very stable and takes some time to complete. Would it be helpfull?

**Comment by callmehiphop** [comment]
I think if the test can take up to several minutes to run, it might not be something we want. Or if we do we might want to conditionally run it based on an env. var or similar.

@stephenplusplus WDYT?

**Comment by stephenplusplus** [comment]
I think it's okay to open the PR, even if we don't merge it. It would be helpful to see a reproduction test case that we can all run.

**Comment by muryginm** [comment]
I will do it within a couple of days when I have time for it

**Comment by muryginm** [comment]
@callmehiphop I added PR with the issue test. You could use it to get the issue in your environment.

**Comment by callmehiphop** [comment]
My understanding is that re-deliveries are just something to expect, I've made some adjustments to hopefully lower the overall percentage (I've been seeing 0~5% redelivered in my local testing), so I'm going to close this issue.
