### ISSUE TITLE
Pull subscriber receives messages even after purging!

### ISSUE THREAD

**Issue by saharshjain** [googleapis/nodejs-pubsub#905]
#### Environment details
  App engine template 

> service: "my server name"
> runtime: nodejs
> env: flex
> resources:
>   cpu: 2
>   memory_gb: 4
>   disk_size_gb: 10
> network:
>   name: default
> manual_scaling:
>   instances: 1

Package.json

> {
>     "dependencies":{
>         "@google-cloud/pubsub":"1.5.0",
>         "axios":"^0.19.2",
>         "csv-parse":"^4.8.5",
>         "dotenv":"^8.2.0",
>         "google-gax":"1.14.1",
>         "googleapis":"47.0.0",
>         "html-to-text":"^5.1.1",
>         "moment":"^2.24.0",
>         "nylas":"^4.9.0",
>         "path":"^0.12.7",
>         "pg":"^7.18.1",
>         "winston":"^3.0.0"
>     },
>     "devDependencies":{
>         "eslint":"^6.8.0",
>         "eslint-config-airbnb-base":"^14.0.0",
>         "eslint-plugin-import":"^2.20.1"
>     }
> }

#### Steps to reproduce
 I am using GCP App engine to deploy a server 
Operation of server can be understood in the [question](https://stackoverflow.com/questions/60297471/publishing-more-than-actual-messages-in-google-pub-sub-using-node-js-and-csv-par/60306869#60306869)
STR
  1.  Due to some error(fixed by the answer in question) my publisher published 150K message instead of actual ~10K
  2. Now being in production environment I purged them all immediately otherwise users might have got affected. 
3. Even after successful purging my subscriber was able to pull messages more than 1000 messages and process them. 
4. Eventually after an hour of trying I had to delete the subscription and recreate it to stop messages from getting pulled.

Subscription specs

> expiry - never expire
> ack timeout  - 120 seconds
> retain ack messages - yes

Sorry I could not format specs 
![Screenshot 2020-02-28 at 1 25 30 PM](https://user-images.githubusercontent.com/10156548/75521591-16754100-5a2e-11ea-947b-24eb23ed1651.png)
in code style.

**Comment by feywind** [comment]
@saharshjain Thanks for the report! Two questions for you:

1) When you say you purged the old messages, do you mean you clicked the purge button in the GCP control panel page (or something similar)?

2) Was the publisher still running while you were trying to purge? By which I mean, the publisher service had sent all of its messages, but the Node process was still running. It's possible that old async operations were still trying to complete for sending the queued messages.

**Comment by saharshjain** [comment]
@feywind  Your most welcome. 

Ans. 1 - Yes, purged those messages. Used purge button on GCP Panel. 

Ans. 2 - No my publisher was done sending the messages. Yes publisher had sent all the messages and my listener started working on them. Then I purged them all and for a significant amount of time the listener was working and still receiving those messages. 
If the node processor was still publishing the messages I could see some numbers in the graph but there wasn't any.

**Comment by feywind** [comment]
@kamalaboulhosn I'm wondering if there's a service issue here, because hitting the purge button in the GCP site seems like it should be independent of the client library. The only other thing I can think of is if the messages are being cached and fed to the application on the client side (or if they're queued up for streaming on the server side).

It's possible, too, that something in the client library is streaming down all of the messages and buffering them until the app can receive them. But I figured I'd see what you thought about the purge button question before pursuing that.

**Comment by kamalaboulhosn** [comment]
@feywind Most likely, there were some messages already buffered to be sent to the client (and potentially in the client itself, e.g., the gRPC buffer) and these are the messages that were delivered. The purge button would not clear out those buffers. Additionally, the purge does not happen synchronously at the moment the button is pressed. With the distributed and asynchronous nature of the operation, it could take time for it to propagate fully and for delivery to stop.

**Comment by feywind** [comment]
Is there anything else that needs to be done here? I merged a fix for the client-based purging a while back, and Kamal's explanation about the purge button in the console is pretty believable, so I'm not sure there's a lot else we can do there.

**Comment by meredithslota** [comment]
I think we are ok to close - based on previous fixes + comments, if folks are still seeing this issue we'd likely need new repro info anyway. :)
